version: "3.9"
services:
  nginx-proxy:
    # image: nginx
    build: ./nginx
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80" # localhost port 80 to container port 80
      - "443:443"
      # - "8080:80" # binds localhost port 8080 to 80 (used for testing)
    depends_on:
      - gunicorn-flask
    networks:
      - my-network
    links:
      - gunicorn-flask

  gunicorn-flask:
    build: ./flask-app
    hostname: gunicorn-flask
    container_name: gunicorn-flask
    # ports:
    #   - "8000:5000"
    networks:
      - my-network

networks:
  my-network:
    ipam:
      driver: default