version: "3.9"
services:
  nginx-proxy:
    # image: nginx
    build: ./nginx
    hostname: nginx
    container_name: nginx
    ports:
      - "8080:80" # binds localhost port 8080 to 80
      # - "8443:443"
      # - "80:80", "443:443"
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gunicorn-flask
    networks:
      - my-network
    links:
      - gunicorn-flask

  gunicorn-flask:
    build: ./flask-app
    hostname: gunicorn-flask
    container_name: gunicorn-flask
    ports:
      - "8000:5000"
    networks:
      - my-network

networks:
  my-network:
    ipam:
      driver: default

    # - "8081:443" # binds localhost port 8081 to 443
  # restart: always 